name: receptico
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  dio: ^5.7.0
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  form_validator: ^2.1.1
  talker_flutter: ^4.5.2
  talker_dio_logger: ^4.5.2
  talker_bloc_logger: ^4.5.2
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13

flutter:
  assets:
    - assets/icons/logo.svg
    - assets/icons/google_logo.svg
    - assets/icons/apple_logo.svg
  uses-material-design: true
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
        - asset: assets/fonts/SFProText-Bold.ttf
flutter_intl:
  enabled: true
