// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7sTWkZM78sd-ouLZ_AtHyPMZfnGoCWV4',
    appId: '1:923605008834:web:5fc4df0d469ee59183165b',
    messagingSenderId: '923605008834',
    projectId: 'receptico-2d43d',
    authDomain: 'receptico-2d43d.firebaseapp.com',
    storageBucket: 'receptico-2d43d.firebasestorage.app',
    measurementId: 'G-VF5SEV5KN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASb-32AkFHErVSy4LvWwzSozzbeOnTrq8',
    appId: '1:923605008834:android:b77fc3b77bc7f7f583165b',
    messagingSenderId: '923605008834',
    projectId: 'receptico-2d43d',
    storageBucket: 'receptico-2d43d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDutkBstVvGI1lg5lXMSM2nc8lm8kG0oTw',
    appId: '1:923605008834:ios:37f2c84c714c3c4083165b',
    messagingSenderId: '923605008834',
    projectId: 'receptico-2d43d',
    storageBucket: 'receptico-2d43d.firebasestorage.app',
    iosBundleId: 'com.GZone.receptico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDutkBstVvGI1lg5lXMSM2nc8lm8kG0oTw',
    appId: '1:923605008834:ios:37f2c84c714c3c4083165b',
    messagingSenderId: '923605008834',
    projectId: 'receptico-2d43d',
    storageBucket: 'receptico-2d43d.firebasestorage.app',
    iosBundleId: 'com.GZone.receptico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7sTWkZM78sd-ouLZ_AtHyPMZfnGoCWV4',
    appId: '1:923605008834:web:a3bb67b882a6af3e83165b',
    messagingSenderId: '923605008834',
    projectId: 'receptico-2d43d',
    authDomain: 'receptico-2d43d.firebaseapp.com',
    storageBucket: 'receptico-2d43d.firebasestorage.app',
    measurementId: 'G-9NMJDNBHX5',
  );
}
